permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Brownian Motion"
id : "" # changeme
description : "Short description" # changeme
thumb: "thumb.gif" # changeme
version: "0.0.1"

ml_url: "http://minutelabs.io"
ml_library: "http://labs.minutelabs.io/library"
ml_assets: "http://labs.minutelabs.io/assets"
library_path: "library" # changeme

show :
  branding: true
  details: true
  comments: false

